version: '3'
services:

  nginx-app:
    build:
      context: docker/development/nginx
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - redis

  php-fpm:
    build:
      context: docker/development/php-fpm
    volumes:
      - ./:/var/www

  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    ports:
      - "54321:5432"

  redis:
    image: redis:3.0

volumes:
  pgdata:
